name: Yon Zilch
avatar: https://static.yon.im/images/avatar.webp # Avatar image. Default to "images/profile.webp".
bio: ' "Memento mori." '
# company: Company # HTML markup are supported, such as: <a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>.
location: げんそうきょう♂ # HTML markup are supported, such as: <a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>.
# about: https://yon.im/about # The external about page. The internal about page will be used if not set.
params: {
  # layout: compacst
}
# See https://hbs.razonyang.com/v1/en/docs/widgets/social-links/.
social:
  email: zilch@yon.im
#  github: yonzilch
#  twitter: razonyang
#  patreon: razonyang
#  paypal: razonyang
  rss: "https://blog.yon.im/index.xml" # Remove RSS
