//// Built-in configuration defaults for Arata.
////
//// This module contains only framework-owned default values. User-owned
//// configuration is defined in `content/arata.toml` and is applied by the
//// configuration resolver.
////
//// Defaults are exposed as primitive values and tuples where possible. This
//// prevents a dependency cycle between the public `config` module and this
//// module:
////
////   config
////     -> config/defaults
////
//// `config/defaults` must therefore not import `config`.
////
//// The default social list intentionally excludes RSS. RSS is a managed social
//// entry derived from the resolved `rss_enabled` value.

import data/site.{
  type Analytics, type CommentsConfig, AnalyticsDisabled, CommentsDisabled,
}
import gleam/option.{type Option, None, Some}

/// Default public URL of the deployed site.
///
/// The configuration resolver is responsible for canonicalizing this value
/// before deriving the deployment base path.
pub fn base_url() -> String {
  "https://arata.yon.im"
}

/// Default site title.
pub fn title() -> String {
  "Arata"
}

/// Default site description.
pub fn description() -> String {
  "A modern and minimalistic blog theme"
}

/// Default navigation items in display order.
///
/// Each tuple contains:
///
///   #(name, url)
///
/// URLs remain unresolved here. The configuration resolver is responsible for
/// applying the deployment base path to internal root-relative URLs.
pub fn menu() -> List(#(String, String)) {
  [
    #("about", "/about"),
    #("links", "/links"),
    #("posts", "/posts"),
    #("projects", "/projects"),
    #("tags", "/tags"),
  ]
}

/// Default user-defined social links in display order.
///
/// Each tuple contains:
///
///   #(name, url, icon)
///
/// The icon value is the SVG filename without its extension under
/// `static/icons/social/`.
///
/// RSS is excluded because it is a managed social entry controlled by
/// `rss_enabled`.
pub fn socials() -> List(#(String, String, String)) {
  [
    #("Codeberg", "https://codeberg.org/yonzilch/arata", "codeberg"),
    #("GitHub", "https://github.com/yonzilch/arata", "github"),
  ]
}

/// Managed RSS social entry.
///
/// The configuration resolver adds this entry only when RSS is enabled.
pub fn rss_social() -> #(String, String, String) {
  #("RSS", "/rss.xml", "rss")
}

/// Default optional navigation logo.
///
/// `None` renders the site title as a text link.
pub fn logo() -> Option(String) {
  None
}

/// Default optional favicon.
///
/// Asset paths remain unresolved here. The configuration resolver is
/// responsible for applying the deployment base path when required.
pub fn favicon() -> Option(String) {
  Some("/images/arata-logo.avif")
}

/// Default optional Fediverse creator attribution.
pub fn fediverse_creator() -> Option(String) {
  None
}

/// Whether RSS and Atom feeds are generated by default.
pub fn rss_enabled() -> Bool {
  True
}

/// Default body text font-family declaration.
pub fn text_font() -> String {
  "-apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Oxygen, Ubuntu, Cantarell, sans-serif"
}

/// Default heading font-family declaration.
pub fn header_font() -> String {
  "-apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Oxygen, Ubuntu, Cantarell, sans-serif"
}

/// Default code font-family declaration.
pub fn code_font() -> String {
  "ui-monospace, \"Cascadia Code\", \"Source Code Pro\", Menlo, Consolas, \"DejaVu Sans Mono\", monospace"
}

/// Default analytics configuration.
pub fn analytics() -> Analytics {
  AnalyticsDisabled
}

/// Default comments configuration.
pub fn comments() -> CommentsConfig {
  CommentsDisabled
}

/// Whether in-page search is enabled by default.
pub fn search_enabled() -> Bool {
  True
}

/// Whether the navigation bar remains fixed by default.
pub fn navbar_fixed() -> Bool {
  True
}

/// Whether MathJax rendering is enabled by default.
pub fn mathjax_enabled() -> Bool {
  True
}

/// Default MathJax runtime asset URL.
pub fn mathjax_url() -> String {
  "https://cdn.jsdelivr.net/npm/mathjax@4.1.3/tex-chtml.js"
}

/// Whether Mermaid rendering is enabled by default.
pub fn mermaid_enabled() -> Bool {
  True
}

/// Default Mermaid ESM runtime asset URL.
pub fn mermaid_url() -> String {
  "https://cdn.jsdelivr.net/npm/mermaid@11.16.0/dist/mermaid.esm.min.mjs"
}

/// Whether runtime syntax highlighting is enabled by default.
pub fn syntax_highlight_enabled() -> Bool {
  True
}

/// Default Highlight.js runtime asset URL.
pub fn syntax_highlight_url() -> String {
  "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.11.1/build/es/highlight.min.js"
}

/// Whether the post sidebar is enabled by default.
pub fn sidebar_enabled() -> Bool {
  True
}

/// Whether floating post controls are enabled by default.
pub fn floating_buttons_enabled() -> Bool {
  True
}

/// Whether the homepage aratafetch summary is enabled by default.
pub fn aratafetch_enabled() -> Bool {
  True
}

/// Default optional value for the aratafetch `maintained` row.
pub fn aratafetch_maintained_for() -> Option(String) {
  Some("since 2026-06-21")
}

/// Whether the Markdown image lightbox is enabled by default.
pub fn lightbox_enabled() -> Bool {
  True
}

/// Whether the homepage latest-posts section is enabled by default.
pub fn latest_posts_enabled() -> Bool {
  False
}

/// Default maximum number of posts in the homepage latest-posts section.
pub fn latest_posts_count() -> Int {
  5
}
