//// Site configuration: title, description, navigation menu, socials, and logo.
////
//// This module mirrors the shape of apollo's `config.toml` `[extra]` block.
//// For now it returns hardcoded defaults; Phase 4 replaces `default/0` with a
//// JSON loader that reads a `config.json` shipped alongside the content index.
////
//// The `Social.icon` field is the filename (without extension) of an SVG in
//// `static/icons/social/` — e.g. `icon: "github"` resolves to
//// `/icons/social/github.svg`. This matches apollo's `get_url(path='icons/social/' ~ social.icon ~ '.svg')`.

import data/site.{
  type Analytics, type SiteMeta, AnalyticsDisabled, CommentsDisabled, SiteMeta,
}
import gleam/list
import gleam/option.{type Option, None, Some}
import gleam/string

pub type Social {
  Social(name: String, url: String, icon: String)
}

pub type MenuItem {
  MenuItem(name: String, url: String)
}

/// Font family configuration. The values are CSS `font-family` declarations.
///
/// Optional fonts users can install and configure:
/// - **Maple Font** (https://github.com/subframe7536/maple-font): A programming
///   font with ligatures. Set `code` to `"\"Maple Mono NF\", \"Maple Mono\", monospace"`.
/// - **Sarasa Gothic** (https://github.com/be5invis/sarasa-gothic): A CJK-friendly
///   font. Set `text` to `"\"Sarasa Gothic SC\", sans-serif"` or
///   `code` to `"\"Sarasa Mono SC\", monospace"`.
pub type Fonts {
  Fonts(text: String, header: String, code: String)
}

pub type Config {
  Config(
    title: String,
    description: String,
    /// Base path for subdirectory deployments.
    ///
    /// Use "" for root deployments:
    ///   https://example.com/
    ///
    /// Use "/arata" for GitHub Pages project deployments:
    ///   https://yonzilch.github.io/arata/
    base_path: String,
    menu: List(MenuItem),
    socials: List(Social),
    /// Optional logo path (relative to `/`). When `None`, the site title is
    /// rendered as a text link in the nav.
    logo: Option(String),
    /// Optional favicon path. Use an absolute path like `/icons/favicon.png`
    /// or `/images/favicon.svg`. When `None`, falls back to `/icon/favicon.png`.
    favicon: Option(String),
    /// Whether RSS/Atom feeds are generated by the build pipeline. When `False`,
    /// no `atom.xml` / `rss.xml` are written to `dist/`, no feed `<link>` tags
    /// are emitted in `index.html`, and the RSS social link is omitted from
    /// the header. Mirrors blogatto's opt-out feed model.
    rss_enabled: Bool,
    /// Font family overrides for body text, headings, and code blocks. The
    /// values are emitted as a `:root` CSS override in the SPA view so the
    /// rest of `arata.css` resolves them through the `--text-font`,
    /// `--header-font`, and `--code-font` custom properties.
    fonts: Fonts,
    /// Whether the in-page search modal is enabled. When `False`, the search
    /// button is omitted from the header, the search modal is not rendered,
    /// and the Cmd/Ctrl+K keyboard shortcut is not subscribed to.
    search_enabled: Bool,
    /// Analytics provider for the SPA runtime. Defaults to `AnalyticsDisabled`;
    /// set to `GoatCounter` or `Umami` to inject the provider's script at boot.
    /// This mirrors `SiteMeta.analytics` so analytics can be configured from
    /// `config.gleam` rather than only from `data/site.gleam`.
    analytics: Analytics,
    /// Whether MathJax typesetting runs on post pages. When `False`, the
    /// MathJax typeset effect is skipped (no MathJax script injection/queue
    /// on post navigation) — useful when no post uses LaTeX. Defaults to
    /// `False` to avoid loading MathJax unless explicitly opted in.
    mathjax_enabled: Bool,
    /// Whether the right sidebar (Tags + ToC) is rendered on post pages.
    /// When `False`, `view_tags_and_toc` is omitted so the post body takes
    /// the full content width. Defaults to `True` so the sidebar shows on
    /// every post unless explicitly disabled.
    sidebar_enabled: Bool,
    /// Whether the floating buttons (the ToC/tags FAB and the overlay's
    /// scroll-to-top button) are rendered. When `False`, no FAB is shown
    /// and the overlay is not reachable. Defaults to `True`.
    floating_buttons_enabled: Bool,
    /// Whether to show the aratafetch ASCII summary on the homepage.
    /// When `False`, the homepage behaves exactly as before.
    aratafetch_enabled: Bool,
    /// Optional display string for aratafetch's "maintained" row.
    /// Example: Some("since 2026-06-21")
    aratafetch_maintained_for: Option(String),
    lightbox_enabled: Bool,
    latest_posts_enabled: Bool,
    latest_posts_count: Int,
  )
}

/// Hardcoded default site metadata used by the build pipeline and SPA runtime.
pub fn site_meta() -> SiteMeta {
  SiteMeta(
    base_url: "https://blog.yon.im",
    title: "Yon Zilch",
    description: "This is Yonzilch's blog",
    analytics: AnalyticsDisabled,
    comments: CommentsDisabled,
    fediverse_creator: None,
    rss_enabled: True,
  )
}

/// Hardcoded default config. Replaced by JSON loading in Phase 4.
pub fn default() -> Config {
  let meta = site_meta()
  let base_path = base_path_from_url(meta.base_url)
  let rss_enabled = meta.rss_enabled

  Config(
    title: meta.title,
    description: meta.description,
    base_path: base_path,
    menu: [
      MenuItem(name: "posts", url: "/posts"),
      MenuItem(name: "links", url: "/links"),
    ],
    // The RSS social link is only added when `rss_enabled` is `True`. Fix
    // 9b/10: the URL is absolute (`/atom.xml`) so it resolves correctly on
    // every page (a relative `./atom.xml` would 404 on sub-pages like
    // `/posts/markdown`, where it expands to `/posts/atom.xml`). The header
    // view (`view_socials`) adds `target="_blank"` to social links so modem
    // (the SPA router) does not intercept the click and the browser fetches
    // the feed directly. Subdirectory-hosted deployments should configure a
    // base URL prefix instead of relying on a relative path.
    socials: default_socials(rss_enabled),
    logo: None,
    favicon: Some("images/avatar.avif"),
    rss_enabled:,
    fonts: Fonts(
      text: "-apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Oxygen, Ubuntu, Cantarell, sans-serif",
      header: "-apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Oxygen, Ubuntu, Cantarell, sans-serif",
      // Fix 9b — default the code font to the browser's native monospace
      // (`ui-monospace`) first, then fall back to common code-editor fonts
      // (Cascadia Code, Source Code Pro), then OS monospace defaults
      // (Menlo/Consolas/DejaVu Sans Mono), and finally the generic
      // `monospace` family. This matches what VS Code and Zed use by
      // default and respects the user's OS-level monospace preference.
      code: "ui-monospace, \"Cascadia Code\", \"Source Code Pro\", Menlo, Consolas, \"DejaVu Sans Mono\", monospace",
    ),
    search_enabled: True,
    analytics: AnalyticsDisabled,
    mathjax_enabled: False,
    sidebar_enabled: True,
    floating_buttons_enabled: True,
    aratafetch_enabled: True,
    aratafetch_maintained_for: Some("since 2023-03-28"),
    lightbox_enabled: True,
    latest_posts_enabled: True,
    latest_posts_count: 20,
  )
}

/// Build the default socials list, conditionally including the RSS link based
/// on `rss_enabled`. This keeps the RSS toggle local to `config.gleam` so the
/// header view (`view/header.gleam`) can stay agnostic — it just renders
/// whatever `socials` it receives.
fn default_socials(rss_enabled: Bool) -> List(Social) {
  let rss = case rss_enabled {
    True -> [Social(name: "RSS", url: "/rss.xml", icon: "rss")]
    False -> []
  }

  list.append(rss, [
    Social(
      name: "Codeberg",
      url: "https://codeberg.org/yonzilch",
      icon: "codeberg",
    ),
    Social(name: "GitHub", url: "https://github.com/yonzilch", icon: "github"),
    Social(
      name: "matrix",
      url: "https://matrix.to/#/@yonzilch:matrix.org",
      icon: "matrix",
    ),
    Social(name: "Telegram", url: "https://t.me/yonzilch", icon: "telegram"),
  ])
}

/// Derive a deployment base path from `SiteMeta.base_url`.
///
/// Examples:
///   https://example.com        -> ""
///   https://example.com/       -> ""
///   https://user.github.io/arata -> "/arata"
///
/// This keeps GitHub Pages project deployments working without hardcoding
/// root-absolute asset URLs like `/app.mjs`.
pub fn base_path_from_url(url: String) -> String {
  let cleaned =
    url
    |> string.trim
    |> trim_trailing_slashes

  case string.split_once(cleaned, "://") {
    Ok(#(_scheme, rest)) -> base_path_from_host_and_path(rest)

    Error(_) -> normalize_base_path(cleaned)
  }
}

fn base_path_from_host_and_path(rest: String) -> String {
  case string.split_once(rest, "/") {
    Ok(#(_host, path)) -> normalize_base_path("/" <> path)

    Error(_) -> ""
  }
}

/// Normalize a deployment base path.
///
/// Examples:
///   ""        -> ""
///   "/"       -> ""
///   "arata"   -> "/arata"
///   "/arata/" -> "/arata"
pub fn normalize_base_path(path: String) -> String {
  path
  |> string.trim
  |> ensure_leading_slash
  |> trim_trailing_slashes
  |> normalize_root_path
}

/// Prefix a root-relative site path with a deployment base path.
///
/// Examples:
///   with_base_path("", "/app.mjs")       -> "/app.mjs"
///   with_base_path("/arata", "/app.mjs") -> "/arata/app.mjs"
///   with_base_path("/arata", "/")        -> "/arata/"
pub fn with_base_path(base_path: String, path: String) -> String {
  let base_path = normalize_base_path(base_path)

  case base_path, path {
    "", _ -> ensure_leading_slash(path)

    _, "/" -> base_path <> "/"

    _, _ -> base_path <> ensure_leading_slash(path)
  }
}

fn ensure_leading_slash(path: String) -> String {
  case path {
    "" -> ""

    _ ->
      case string.starts_with(path, "/") {
        True -> path
        False -> "/" <> path
      }
  }
}

fn trim_trailing_slashes(path: String) -> String {
  case string.ends_with(path, "/") {
    True -> {
      let size = string.length(path)

      path
      |> string.slice(0, size - 1)
      |> trim_trailing_slashes
    }

    False -> path
  }
}

fn normalize_root_path(path: String) -> String {
  case path {
    "/" -> ""
    _ -> path
  }
}
