name: Sync From FIRST S3 Bucket to SECOND S3 Bucket

on:
  push:
    branches:
      - main

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS CLI for FIRST
        env:  
          FIRST_ACCESS_KEY: ${{ secrets.FIRST_ACCESS_KEY }}
          FIRST_SECRET_KEY: ${{ secrets.FIRST_SECRET_KEY }}
          FIRST_REGION: ${{ secrets.FIRST_REGION }}
          FIRST_ENDPOINT: ${{ secrets.FIRST_ENDPOINT }}
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = $FIRST_ACCESS_KEY" >> ~/.aws/credentials
          echo "aws_secret_access_key = $FIRST_SECRET_KEY" >> ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "region = $FIRST_REGION" >> ~/.aws/config
          echo "s3 =" >> ~/.aws/config
          echo "    endpoint_url = $FIRST_ENDPOINT" >> ~/.aws/config

      - name: Sync from FIRST to local
        env:
          FIRST_BUCKET: ${{ secrets.FIRST_BUCKET }}
        run: |
          aws s3 sync s3://$FIRST_BUCKET ./temp_backup

      - name: Configure AWS CLI for SECOND
        env:
          SECOND_ACCESS_KEY: ${{ secrets.SECOND_ACCESS_KEY }}
          SECOND_SECRET_KEY: ${{ secrets.SECOND_SECRET_KEY }}
          SECOND_REGION: ${{ secrets.SECOND_REGION }}
          SECOND_ENDPOINT: ${{ secrets.SECOND_ENDPOINT }}
        run: |
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = $SECOND_ACCESS_KEY" >> ~/.aws/credentials
          echo "aws_secret_access_key = $SECOND_SECRET_KEY" >> ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "region = $SECOND_REGION" >> ~/.aws/config
          echo "s3 =" >> ~/.aws/config
          echo "    endpoint_url = $SECOND_ENDPOINT" >> ~/.aws/config

      - name: Sync from FIRST to SECOND
        env:
          SECOND_BUCKET: ${{ secrets.SECOND_BUCKET }}
        run: |
          aws s3 sync ./temp_backup s3://$SECOND_BUCKET

      - name: Clean up
        run: |
          rm -rf ./temp_backup
